import type { Activity } from "../types";

export const ACTIVITIES: readonly Activity[] = [
  // ── Quick Evening Ones ─────────────────────────────────────────────────
  {
    id: "dovestone-res",
    name: "Dovestone Reservoir Circuit",
    category: "hike",
    subcategory: "Quick Evening Ones",
    drive: 15,
    durationMin: 1.5,
    durationMax: 2,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Saddleworth",
    halal: false,
    desc: "Water views the whole way round. Golden hour over the reservoir is genuinely unreal — the go-to after-work walk from Oldham.",
    notes: "Free parking on weekdays. June/July sunset ~9:30pm so you can head straight from work.",
  },
  {
    id: "tandle-hill",
    name: "Tandle Hill Sunset",
    category: "hike",
    subcategory: "Quick Evening Ones",
    drive: 10,
    durationMin: 0.75,
    durationMax: 1,
    effort: "chill",
    cost: 1,
    engagement: 3,
    location: "Oldham",
    halal: false,
    desc: "Manchester skyline spread out below you at golden hour. 10 minutes from your door.",
    notes: "Free. Best in June and July when sunset is ~9:30pm.",
  },
  {
    id: "healey-dell",
    name: "Healey Dell",
    category: "hike",
    subcategory: "Quick Evening Ones",
    drive: 15,
    durationMin: 1.5,
    durationMax: 1.5,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Rochdale",
    halal: false,
    desc: "Hidden Victorian viaduct, river gorge and waterfalls that have no business being this dramatic near Rochdale.",
    notes: "Free. Great in evening light.",
  },
  {
    id: "rivington-pike",
    name: "Rivington Pike & Terraced Gardens",
    category: "hike",
    subcategory: "Quick Evening Ones",
    drive: 40,
    durationMin: 1.5,
    durationMax: 2,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Bolton",
    halal: false,
    desc: "Pike tower at the summit plus hidden Japanese-style terraced gardens on the way up. More interesting than it looks on a map.",
    notes: "Free. Combine with Anglezarke Reservoir loop.",
  },
  {
    id: "crompton-moor",
    name: "Crompton Moor",
    category: "hike",
    subcategory: "Quick Evening Ones",
    drive: 10,
    durationMin: 1,
    durationMax: 1.5,
    effort: "light",
    cost: 1,
    engagement: 3,
    location: "Oldham",
    halal: false,
    desc: "Moorland literally on the edge of Oldham with wide-open views over Greater Manchester.",
    notes: "Free. As local as it gets.",
  },
  // ── HALF-DAY HIKES ────────────────────────────────────────────────────
  {
    id: "mam-tor",
    name: "Mam Tor Ridge Walk",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 40,
    durationMin: 3,
    durationMax: 4,
    effort: "moderate",
    cost: 1,
    engagement: 5,
    location: "Peak District",
    halal: false,
    desc: "Knife-edge ridge with dramatic drops either side. Constantly photogenic and one of the most satisfying walks in the Peak District.",
    notes: "Parking ~£5. Combine with Speedwell Cavern for the best full-day combo on the list.",
  },
  {
    id: "stanage-edge",
    name: "Stanage Edge",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 50,
    durationMin: 3,
    durationMax: 4,
    effort: "light",
    cost: 1,
    engagement: 5,
    location: "Peak District",
    halal: false,
    desc: "Iconic gritstone edge that stretches for miles. Climbers on the walls below, boulders to scramble on, cinematic views.",
    notes: "Go early — parking fills fast. Robin Hood's Cave is worth finding along the edge.",
  },
  {
    id: "malham-cove",
    name: "Malham Cove & Gordale Scar",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 75,
    durationMin: 3,
    durationMax: 4,
    effort: "moderate",
    cost: 1,
    engagement: 5,
    location: "Yorkshire Dales",
    halal: false,
    desc: "Massive limestone cliff with a flat pavement on top and a separate gorge with a waterfall. Bucket list.",
    notes: "Free. Village café in Malham after. Both landmarks done in one loop.",
  },
  {
    id: "ingleton-falls",
    name: "Ingleton Waterfalls Trail",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 85,
    durationMin: 2.5,
    durationMax: 3,
    effort: "light",
    cost: 2,
    engagement: 5,
    location: "Yorkshire Dales",
    halal: false,
    desc: "A series of waterfalls through woodland — constant visual payoff the entire way. Never boring for a minute.",
    notes: "Entry ~£8. Pair with White Scar Cave nearby for the ideal Yorkshire day.",
  },
  {
    id: "catbells",
    name: "Catbells",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 105,
    durationMin: 2,
    durationMax: 2,
    effort: "light",
    cost: 1,
    engagement: 5,
    location: "Lake District",
    halal: false,
    desc: "Short summit with jaw-dropping views over Derwentwater. Best effort-to-reward ratio in the entire Lake District.",
    notes: "Parking at Gutherscale. Take the Keswick ferry for a more memorable approach.",
  },
  {
    id: "cwm-idwal",
    name: "Cwm Idwal",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 120,
    durationMin: 1.5,
    durationMax: 2,
    effort: "light",
    cost: 1,
    engagement: 5,
    location: "Snowdonia",
    halal: false,
    desc: "Glacial lake completely surrounded by dramatic cliffs. Jaw-dropping scenery for very little effort.",
    notes: "Parking at Ogwen Valley. Also the start of the Tryfan scramble if you want more.",
  },
  {
    id: "the-roaches",
    name: "The Roaches",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 55,
    durationMin: 3,
    durationMax: 3,
    effort: "moderate",
    cost: 1,
    engagement: 4,
    location: "Staffordshire Moorlands",
    halal: false,
    desc: "Gritstone ridge with bouldering spots the whole way. Quieter than Kinder. Wallabies have lived here since the 1930s.",
    notes: "Parking at Roach End. The wallabies escaped from a private zoo and never left.",
  },
  {
    id: "kinder-downfall",
    name: "Kinder Downfall",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 35,
    durationMin: 4,
    durationMax: 5,
    effort: "moderate",
    cost: 1,
    engagement: 4,
    location: "Peak District",
    halal: false,
    desc: "Waterfall off the edge of the Kinder plateau. On windy days the water gets blown back upwards.",
    notes: "Start from Hayfield. Check the weather before heading out.",
  },
  {
    id: "bolton-abbey",
    name: "Bolton Abbey & The Strid",
    category: "hike",
    subcategory: "Half-Day Hike",
    drive: 60,
    durationMin: 2,
    durationMax: 3,
    effort: "light",
    cost: 2,
    engagement: 4,
    location: "Yorkshire Dales",
    halal: false,
    desc: "Medieval priory ruins on a woodland river walk. The Strid looks jumpable but has genuinely claimed lives — look, don't try.",
    notes: "Parking ~£12. Café on site.",
  },
  // ── FULL-DAY CHALLENGES ───────────────────────────────────────────────
  {
    id: "helvellyn",
    name: "Helvellyn via Striding Edge",
    category: "hike",
    subcategory: "Full-Day Challenge",
    drive: 100,
    durationMin: 5,
    durationMax: 6,
    effort: "hard",
    cost: 1,
    engagement: 5,
    location: "Lake District",
    halal: false,
    desc: "Knife-edge ridge scramble with sheer drops either side. Real adrenaline on the ascent, real bragging rights at the summit.",
    notes: "Start from Patterdale or Glenridding. Do not attempt in wet or icy conditions.",
  },
  {
    id: "snowdon",
    name: "Snowdon (Yr Wyddfa)",
    category: "hike",
    subcategory: "Full-Day Challenge",
    drive: 120,
    durationMin: 5,
    durationMax: 6,
    effort: "moderate",
    cost: 1,
    engagement: 5,
    location: "Snowdonia",
    halal: false,
    desc: "Wales' highest peak. Multiple routes, café at the summit. One of the most iconic climbs in Britain.",
    notes: "Start early — extremely busy in summer. Pyg Track is more scenic than Llanberis.",
  },
  {
    id: "tryfan",
    name: "Tryfan Scramble",
    category: "hike",
    subcategory: "Full-Day Challenge",
    drive: 120,
    durationMin: 4,
    durationMax: 5,
    effort: "hard",
    cost: 1,
    engagement: 5,
    location: "Snowdonia",
    halal: false,
    desc: "Hands-on scramble the entire way. Two rock pillars at the summit — Adam & Eve — to jump between if you dare.",
    notes: "No path, just rock. Not for anyone with heights issues.",
  },
  {
    id: "three-peaks",
    name: "Yorkshire Three Peaks",
    category: "hike",
    subcategory: "Full-Day Challenge",
    drive: 80,
    durationMin: 10,
    durationMax: 12,
    effort: "very-hard",
    cost: 1,
    engagement: 5,
    location: "Yorkshire Dales",
    halal: false,
    desc: "24 miles. 3 summits. One day. Pen-y-ghent, Whernside, Ingleborough. The ultimate summer group challenge.",
    notes:
      "Start at Horton-in-Ribblesdale. Emergency food, rain gear, battery packs. Train beforehand.",
  },
  {
    id: "kinder-scout",
    name: "Kinder Scout via Grindsbrook",
    category: "hike",
    subcategory: "Full-Day Challenge",
    drive: 35,
    durationMin: 4,
    durationMax: 5,
    effort: "hard",
    cost: 1,
    engagement: 4,
    location: "Peak District",
    halal: false,
    desc: "The Peak District's highest point. Boggy moorland plateau that is genuinely disorientating and remote.",
    notes: "Parking at Edale ~£5. Start early. The plateau is hard to navigate without GPS.",
  },
  // ── CITY TRIPS ────────────────────────────────────────────────────────
  {
    id: "nq-wander",
    name: "Northern Quarter Wander",
    category: "city",
    subcategory: "Local",
    drive: 25,
    durationMin: 2,
    durationMax: 3,
    effort: "chill",
    cost: 1,
    engagement: 4,
    location: "Manchester",
    halal: true,
    desc: "Street art, Afflecks for vintage finds, independent coffee spots, record stores. Good for an afternoon with no agenda.",
    notes: "Rusholme Curry Mile is 10 min away. NQ also has its own independent halal spots.",
  },
  {
    id: "stadium-tour",
    name: "Stadium Tour — OT or Etihad",
    category: "city",
    subcategory: "Local",
    drive: 30,
    durationMin: 1.5,
    durationMax: 2,
    effort: "chill",
    cost: 2,
    engagement: 4,
    location: "Manchester",
    halal: false,
    desc: "Tunnel, pitch, dressing room. Even as a Chelsea man it is worth doing once purely for the experience.",
    notes: "~£25–30pp. Book ahead — popular in summer. Both Old Trafford and Etihad offer similar.",
  },
  {
    id: "saddleworth",
    name: "Saddleworth Village Hop",
    category: "city",
    subcategory: "Local",
    drive: 15,
    durationMin: 2,
    durationMax: 3,
    effort: "chill",
    cost: 1,
    engagement: 3,
    location: "Oldham",
    halal: false,
    desc: "Uppermill, Dobcross, Delph — stone villages, canal walks, countryside views. Right on your doorstep.",
    notes: "Free. Good for a casual afternoon that needs zero planning.",
  },
  {
    id: "liverpool",
    name: "Liverpool Waterfront Day",
    category: "city",
    subcategory: "City Day Trip",
    drive: 55,
    durationMin: 4,
    durationMax: 6,
    effort: "chill",
    cost: 1,
    engagement: 5,
    location: "Liverpool",
    halal: true,
    desc: "Waterfront walk past the Three Graces and Albert Dock, Bold Street for halal food. A buzzing city with real energy.",
    notes: "Halal on Bold Street. Parking at Liverpool One. Anfield tour optional (~£25).",
  },
  {
    id: "york",
    name: "York — Shambles, Walls & Food",
    category: "city",
    subcategory: "City Day Trip",
    drive: 80,
    durationMin: 5,
    durationMax: 7,
    effort: "chill",
    cost: 2,
    engagement: 5,
    location: "York",
    halal: true,
    desc: "Medieval streets that inspired Diagon Alley, walk the full city walls, great halal food. One of the best day trips on this list.",
    notes: "Halal at Efes or Istanbul near the Shambles. JORVIK Viking Centre optional add-on.",
  },
  {
    id: "chester",
    name: "Chester — Rows, Walls & River",
    category: "city",
    subcategory: "City Day Trip",
    drive: 70,
    durationMin: 4,
    durationMax: 5,
    effort: "chill",
    cost: 1,
    engagement: 4,
    location: "Chester",
    halal: false,
    desc: "Roman streets, medieval two-tier galleries, England's most complete city walls, and a river walk.",
    notes: "Free to walk. Chester Zoo is 10 min away for a longer day.",
  },
  {
    id: "whitby",
    name: "Whitby — Abbey, Harbour & Vibes",
    category: "city",
    subcategory: "Town Day Trip",
    drive: 120,
    durationMin: 4,
    durationMax: 5,
    effort: "chill",
    cost: 2,
    engagement: 5,
    location: "North Yorkshire Coast",
    halal: false,
    desc: "199 steps to the ruined abbey, Dracula connections, jet stone shops, harbour, and fish & chips. Unique atmosphere.",
    notes: "Abbey entry ~£10. Go midweek — busy on summer weekends.",
  },
  {
    id: "harrogate",
    name: "Harrogate Turkish Baths",
    category: "city",
    subcategory: "Town Day Trip",
    drive: 75,
    durationMin: 3,
    durationMax: 4,
    effort: "chill",
    cost: 2,
    engagement: 4,
    location: "Harrogate",
    halal: false,
    desc: "Victorian Turkish baths running since 1897 — hot rooms, plunge pools, complete relaxation. A proper treat.",
    notes: "Book men-only sessions in advance — they sell out. Valley Gardens walk after.",
  },
  {
    id: "llandudno",
    name: "Llandudno — Pier & Great Orme",
    category: "city",
    subcategory: "Town Day Trip",
    drive: 100,
    durationMin: 3,
    durationMax: 4,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "North Wales",
    halal: false,
    desc: "Victorian pier, Great Orme cable car to the summit, sweeping bay views. Classic seaside done properly.",
    notes: "Cable car or tram ~£10. Easy to pair with Conwy Castle 15 min away.",
  },
  {
    id: "leeds",
    name: "Leeds — Kirkgate Market & City",
    category: "city",
    subcategory: "City Day Trip",
    drive: 50,
    durationMin: 3,
    durationMax: 4,
    effort: "chill",
    cost: 1,
    engagement: 3,
    location: "Leeds",
    halal: true,
    desc: "Biggest covered market in Europe, strong halal food scene, good city walk through the Victorian arcades.",
    notes: "Free to walk. Harehills area for the best halal. Trinity Leeds for shops.",
  },
  // ── NATURE ────────────────────────────────────────────────────────────
  {
    id: "speedwell",
    name: "Speedwell Cavern",
    category: "nature",
    subcategory: "Cave",
    drive: 40,
    durationMin: 1,
    durationMax: 1,
    effort: "chill",
    cost: 2,
    engagement: 5,
    location: "Castleton, Peak District",
    halal: false,
    desc: "Underground boat ride through a flooded lead mine. The most unique experience on this list — unlike anything else you can do.",
    notes: "~£18. Book ahead in summer. Best combined with Mam Tor for the perfect full day.",
  },
  {
    id: "white-scar",
    name: "White Scar Cave",
    category: "nature",
    subcategory: "Cave",
    drive: 85,
    durationMin: 1.5,
    durationMax: 1.5,
    effort: "chill",
    cost: 2,
    engagement: 5,
    location: "Ingleton, Yorkshire Dales",
    halal: false,
    desc: "Longest show cave in England with underground waterfalls and jaw-dropping formations throughout.",
    notes: "~£14. Combine with Ingleton Waterfalls Trail above ground.",
  },
  {
    id: "blue-john",
    name: "Blue John Cavern",
    category: "nature",
    subcategory: "Cave",
    drive: 40,
    durationMin: 1,
    durationMax: 1,
    effort: "chill",
    cost: 2,
    engagement: 4,
    location: "Castleton, Peak District",
    halal: false,
    desc: "Guided descent through rare mineral formations found nowhere else on earth. The Blue John stone walls are stunning.",
    notes: "~£15. Do Speedwell + Blue John in a morning, Mam Tor in the afternoon.",
  },
  {
    id: "treak-cliff",
    name: "Treak Cliff Cavern",
    category: "nature",
    subcategory: "Cave",
    drive: 40,
    durationMin: 1,
    durationMax: 1,
    effort: "chill",
    cost: 2,
    engagement: 4,
    location: "Castleton, Peak District",
    halal: false,
    desc: "Stalactites, stalagmites and Blue John stone visible in the walls on a guided tour. Third of the Castleton cave trio.",
    notes: "~£15. All three Castleton caves in one morning is doable before an afternoon hike.",
  },
  {
    id: "formby",
    name: "Formby Beach & Red Squirrel Reserve",
    category: "nature",
    subcategory: "Scenic Spot",
    drive: 60,
    durationMin: 2,
    durationMax: 3,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Merseyside",
    halal: false,
    desc: "Pine forest through sand dunes to a proper beach. Red squirrels year-round. Doesn't feel like the North West.",
    notes: "NT parking ~£8. Get there by 10am on weekends.",
  },
  {
    id: "dovedale",
    name: "Dovedale Stepping Stones",
    category: "nature",
    subcategory: "Scenic Spot",
    drive: 70,
    durationMin: 2,
    durationMax: 3,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Peak District",
    halal: false,
    desc: "River valley walk with stepping stones, limestone pinnacles and small caves throughout.",
    notes: "Free. Busy weekends. Car park at Dovedale.",
  },
  {
    id: "ainsdale",
    name: "Ainsdale Sand Dunes",
    category: "nature",
    subcategory: "Scenic Spot",
    drive: 60,
    durationMin: 2,
    durationMax: 3,
    effort: "light",
    cost: 1,
    engagement: 3,
    location: "Merseyside",
    halal: false,
    desc: "Largest dune system in England. Coastal wilderness that feels genuinely remote, with rare wildlife throughout.",
    notes: "Free. National Nature Reserve — stay on marked paths.",
  },
  {
    id: "rivington-gardens",
    name: "Rivington Terraced Gardens",
    category: "nature",
    subcategory: "Scenic Spot",
    drive: 40,
    durationMin: 2,
    durationMax: 3,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Bolton",
    halal: false,
    desc: "Hidden Japanese-style gardens built in 1900, now half-ruined and atmospheric. Most Mancunians have never heard of them.",
    notes: "Free. Combine with Rivington Pike summit above.",
  },
  {
    id: "conwy",
    name: "Conwy Castle",
    category: "nature",
    subcategory: "Castle",
    drive: 110,
    durationMin: 1.5,
    durationMax: 2,
    effort: "light",
    cost: 2,
    engagement: 5,
    location: "North Wales",
    halal: false,
    desc: "UNESCO World Heritage coastal fortress. Climb every tower, walk the walls, views over the harbour. One of the best castles in Britain.",
    notes: "~£10. Pair with Llandudno 15 min away for a full North Wales day.",
  },
  {
    id: "beeston",
    name: "Beeston Castle",
    category: "nature",
    subcategory: "Castle",
    drive: 70,
    durationMin: 2,
    durationMax: 2,
    effort: "light",
    cost: 2,
    engagement: 4,
    location: "Cheshire",
    halal: false,
    desc: "Hilltop medieval ruin with views across 8 counties on a clear day. Short steep climb, massive payoff.",
    notes: "~£10. Peckforton Castle visible across the valley.",
  },
  {
    id: "peveril",
    name: "Peveril Castle",
    category: "nature",
    subcategory: "Castle",
    drive: 40,
    durationMin: 1,
    durationMax: 1.5,
    effort: "light",
    cost: 2,
    engagement: 4,
    location: "Castleton, Peak District",
    halal: false,
    desc: "Norman keep on a hilltop overlooking Hope Valley. Short sharp climb from the village, great views.",
    notes: "~£8. The obvious add-on to any Castleton cave day.",
  },
  {
    id: "clitheroe",
    name: "Clitheroe Castle & Ribble Valley",
    category: "nature",
    subcategory: "Castle",
    drive: 50,
    durationMin: 1,
    durationMax: 2,
    effort: "light",
    cost: 1,
    engagement: 3,
    location: "Ribble Valley",
    halal: false,
    desc: "12th-century keep with panoramic Ribble Valley views. Grounds free to walk, combine with Whalley Abbey ruins nearby.",
    notes: "Castle museum entry ~£5. Grounds free. Lovely quiet afternoon option.",
  },
  // ── BIG DAYS ──────────────────────────────────────────────────────────
  {
    id: "alton-towers",
    name: "Alton Towers",
    category: "bigday",
    subcategory: "Theme Park",
    drive: 75,
    durationMin: 6,
    durationMax: 8,
    effort: "light",
    cost: 3,
    engagement: 5,
    location: "Staffordshire",
    halal: true,
    desc: "Nemesis Reborn, Smiler, Wicker Man, Oblivion. The best theme park within range — a genuine full day.",
    notes: "Book 7+ days ahead for 40–50% off gate price. Halal food options on site.",
  },
  {
    id: "blackpool-pb",
    name: "Blackpool Pleasure Beach",
    category: "bigday",
    subcategory: "Theme Park",
    drive: 70,
    durationMin: 5,
    durationMax: 7,
    effort: "light",
    cost: 3,
    engagement: 5,
    location: "Blackpool",
    halal: false,
    desc: "Icon, Big One, Valhalla. A proper full day. Combine with the Tower and seafront walk after.",
    notes: "Book in advance. Illuminations from September — worth a return evening visit.",
  },
  {
    id: "knowsley",
    name: "Knowsley Safari Park",
    category: "bigday",
    subcategory: "Safari",
    drive: 50,
    durationMin: 3,
    durationMax: 4,
    effort: "chill",
    cost: 3,
    engagement: 4,
    location: "Merseyside",
    halal: false,
    desc: "Drive-through safari with animals at your windows. The baboons will absolutely try to dismantle your car.",
    notes: "~£22pp. Car required. Foot safari and fairground rides included.",
  },
  {
    id: "flamingo-land",
    name: "Flamingo Land",
    category: "bigday",
    subcategory: "Theme Park",
    drive: 90,
    durationMin: 6,
    durationMax: 7,
    effort: "light",
    cost: 3,
    engagement: 4,
    location: "North Yorkshire",
    halal: false,
    desc: "Theme park and zoo combined. Less packed than Alton Towers, decent rides, more relaxed pace.",
    notes: "~£40pp. Book online in advance. Good fallback if Alton Towers dates are sold out.",
  },
  {
    id: "chester-zoo",
    name: "Chester Zoo",
    category: "bigday",
    subcategory: "Safari",
    drive: 70,
    durationMin: 5,
    durationMax: 6,
    effort: "light",
    cost: 3,
    engagement: 4,
    location: "Cheshire",
    halal: false,
    desc: "One of Europe's top zoos — 500+ species across beautiful grounds. More engaging than you'd expect, genuinely a full day.",
    notes: "~£30–35pp. Book ahead. Easy to combine with Chester city walk.",
  },
  {
    id: "zip-world",
    name: "Zip World, North Wales",
    category: "bigday",
    subcategory: "Adventure",
    drive: 110,
    durationMin: 3,
    durationMax: 4,
    effort: "moderate",
    cost: 4,
    engagement: 5,
    location: "Bethesda, North Wales",
    halal: false,
    desc: "Velocity 2 — the fastest zip line in Europe at 100mph over a slate quarry. Bounce Below underground trampoline also available.",
    notes: "~£50–80pp. Book well ahead. Easy to pair with Conwy or Snowdon.",
  },
  {
    id: "ghyll",
    name: "Ghyll Scrambling, Lake District",
    category: "bigday",
    subcategory: "Water Adventure",
    drive: 100,
    durationMin: 3,
    durationMax: 4,
    effort: "moderate",
    cost: 3,
    engagement: 5,
    location: "Lake District",
    halal: false,
    desc: "Climbing up waterfalls and through gorges in wetsuits with a guide. One of the most fun outdoor activities on this list, full stop.",
    notes: "Various providers near Ambleside. ~£40–50pp. Book in advance.",
  },
  {
    id: "kayaking",
    name: "Kayaking on Windermere",
    category: "bigday",
    subcategory: "Water Adventure",
    drive: 90,
    durationMin: 2,
    durationMax: 3,
    effort: "moderate",
    cost: 2,
    engagement: 5,
    location: "Lake District",
    halal: false,
    desc: "Paddle around the islands on England's largest lake with mountains on every side.",
    notes: "Hire from Low Wood Bay or Windermere Canoe Kayak. ~£20–35pp.",
  },
  {
    id: "surf-snowdonia",
    name: "Surf Snowdonia",
    category: "bigday",
    subcategory: "Water Adventure",
    drive: 110,
    durationMin: 3,
    durationMax: 4,
    effort: "moderate",
    cost: 3,
    engagement: 5,
    location: "Dolgarrog, North Wales",
    halal: false,
    desc: "World's first inland surf lagoon with machine-generated waves. Adventure activities on site too.",
    notes: "~£35–50pp. Summer slots fill fast — book well ahead.",
  },
  {
    id: "karting",
    name: "Go Karting — Three Sisters",
    category: "bigday",
    subcategory: "Competitive",
    drive: 35,
    durationMin: 1.5,
    durationMax: 2,
    effort: "light",
    cost: 3,
    engagement: 5,
    location: "Wigan",
    halal: false,
    desc: "Outdoor circuit with proper racing karts. Best karting near Oldham. Someone always takes it way too seriously.",
    notes: "~£30–50pp. Book a full race package for the group.",
  },
  {
    id: "paintball",
    name: "Paintballing",
    category: "bigday",
    subcategory: "Competitive",
    drive: 40,
    durationMin: 4,
    durationMax: 5,
    effort: "moderate",
    cost: 3,
    engagement: 5,
    location: "Greater Manchester",
    halal: false,
    desc: "Delta Force or NPF. Absolute chaos in the best possible way. Get 10+ lads and split into proper teams.",
    notes: "~£25–40pp. Book ahead for group rates. Bruises are guaranteed.",
  },
  {
    id: "airsoft",
    name: "Airsoft",
    category: "bigday",
    subcategory: "Competitive",
    drive: 40,
    durationMin: 4,
    durationMax: 6,
    effort: "moderate",
    cost: 3,
    engagement: 5,
    location: "Greater Manchester",
    halal: false,
    desc: "More tactical than paintball — military-sim scenarios throughout the day. A proper full-day out.",
    notes: "~£30–45pp. Tactical Warfare and Combat South Manchester are both solid.",
  },
  {
    id: "bouldering",
    name: "Bouldering — The Depot",
    category: "bigday",
    subcategory: "Competitive",
    drive: 25,
    durationMin: 2,
    durationMax: 3,
    effort: "moderate",
    cost: 2,
    engagement: 5,
    location: "Manchester",
    halal: false,
    desc: "No harness, no ropes — just climb. Competitive, skill-building, and once you start you will go back every week.",
    notes: "~£12–15pp. Best climbing facility in Manchester. Beginner-friendly.",
  },
  {
    id: "escape-rooms",
    name: "Escape Rooms, Manchester",
    category: "bigday",
    subcategory: "Competitive",
    drive: 25,
    durationMin: 1,
    durationMax: 1.5,
    effort: "chill",
    cost: 2,
    engagement: 5,
    location: "Manchester",
    halal: false,
    desc: "Book 2 rooms and race each other. Breakout, Escape Reality and The Panic Room are all worth doing.",
    notes: "~£20–25pp. Multiple rooms means you can properly compete.",
  },
  {
    id: "axe-throwing",
    name: "Axe Throwing — Whistle Punks",
    category: "bigday",
    subcategory: "Competitive",
    drive: 25,
    durationMin: 1.5,
    durationMax: 1.5,
    effort: "chill",
    cost: 2,
    engagement: 4,
    location: "Manchester",
    halal: false,
    desc: "Proper league format with a ranking system. More satisfying than it has any right to be.",
    notes: "~£25pp. Ducie Street. No experience needed.",
  },
  {
    id: "go-ape",
    name: "Go Ape (Rivington or Delamere)",
    category: "bigday",
    subcategory: "Adventure",
    drive: 50,
    durationMin: 2,
    durationMax: 3,
    effort: "moderate",
    cost: 3,
    engagement: 4,
    location: "Bolton / Cheshire",
    halal: false,
    desc: "High ropes and zip lines through the forest canopy. Competitive, surprisingly tiring, a genuine laugh.",
    notes: "~£35pp. Rivington is closest from Oldham.",
  },
  {
    id: "trampolining",
    name: "Trampolining — Flip Out / AirKix",
    category: "bigday",
    subcategory: "Competitive",
    drive: 25,
    durationMin: 1.5,
    durationMax: 2,
    effort: "moderate",
    cost: 2,
    engagement: 4,
    location: "Manchester",
    halal: false,
    desc: "Freestyle jumping, slam dunk, dodgeball. More tiring than you'd expect and a solid warm-up activity.",
    notes: "~£12–15pp. Good starter activity before a meal out.",
  },
  // ── CHILL ─────────────────────────────────────────────────────────────
  {
    id: "dovestone-bbq",
    name: "Sunset BBQ at Dovestone",
    category: "chill",
    subcategory: "Chill",
    drive: 15,
    durationMin: 2,
    durationMax: 3,
    effort: "chill",
    cost: 1,
    engagement: 4,
    location: "Saddleworth",
    halal: true,
    desc: "Pack halal meat, portable BBQ, and watch the sun go down over the reservoir. Simple, cheap, unbeatable.",
    notes: "Check current BBQ rules on arrival. June/July sunset ~9:30pm — go straight from work.",
  },
  {
    id: "hollingworth",
    name: "Hollingworth Lake BBQ",
    category: "chill",
    subcategory: "Chill",
    drive: 15,
    durationMin: 2,
    durationMax: 4,
    effort: "chill",
    cost: 1,
    engagement: 3,
    location: "Rochdale",
    halal: true,
    desc: "Lakeside spot with a flat walk around the perimeter. Set up, eat, walk, repeat.",
    notes: "Check BBQ rules on arrival. Watersports hire available at the lake in summer.",
  },
  {
    id: "cricket",
    name: "Cricket or 5-a-side in the Park",
    category: "chill",
    subcategory: "Chill",
    drive: 5,
    durationMin: 2,
    durationMax: 3,
    effort: "light",
    cost: 1,
    engagement: 4,
    location: "Oldham",
    halal: false,
    desc: "Grab a cricket set or a ball, find a park. Free, social, timeless.",
    notes: "Free. A cricket set costs ~£20 if you need one — worth it for the whole summer.",
  },
  {
    id: "ziferblat",
    name: "Board Games — Ziferblat",
    category: "chill",
    subcategory: "Chill",
    drive: 25,
    durationMin: 2,
    durationMax: 3,
    effort: "chill",
    cost: 2,
    engagement: 4,
    location: "Manchester",
    halal: false,
    desc: "Pay by the minute, hundreds of board games, unlimited coffee and snacks. The perfect rainy day fallback.",
    notes: "~£6 per hour. Edge Street, Northern Quarter. No booking needed.",
  },
  {
    id: "stargazing",
    name: "Stargazing at Tegg's Nose",
    category: "chill",
    subcategory: "Chill",
    drive: 40,
    durationMin: 1.5,
    durationMax: 2,
    effort: "chill",
    cost: 1,
    engagement: 3,
    location: "Macclesfield",
    halal: false,
    desc: "Low light pollution, open sky, late summer clear nights. Download a star map app beforehand.",
    notes: "Free. Best July–August. Check sky quality apps before making the drive.",
  },
  {
    id: "geocaching",
    name: "Geocaching (Anywhere)",
    category: "chill",
    subcategory: "Chill",
    drive: 5,
    durationMin: 1,
    durationMax: 3,
    effort: "light",
    cost: 1,
    engagement: 3,
    location: "Anywhere",
    halal: false,
    desc: "GPS treasure-hunting that makes any walk more interesting. Surprisingly addictive once you find the first one.",
    notes: "Free (Geocaching app). Caches hidden everywhere including right in Oldham.",
  },
];
